"""Run the demolition-indicator ablation.

Each indicator in ``indicators.py`` returns only ``building_id`` + ``year`` — the
*membership* of the demolished set under that definition. This driver attaches the
outcome measures the article reports (``docs/indicators.md`` "Ablation scope") and
sweeps the full 12-cell variant grid (``all_variants``):

    - counts        — one row per candidate building after the shared negative-area filter
    - demolished m² — primary area outcome = byg038SamletBygningsareal
    - coverage %    — the fraction of demolished buildings with non-null total area.
                      Missing total area is retained for counts, contributes no m², and is
                      reported openly; zero is retained as a recorded zero-area value.

Per-building attributes (area, use-code, region, construction year) are rolled up from
``bygning.parquet`` here — this is aggregation plumbing, not a demolition decision, so it
lives in the driver, never in an indicator (the indicators stay pure per the article's
"no opaque contract" principle).

Negative total-area values are excluded after candidate-event detection using the same rule
for every indicator. Zero total-area values are retained. Construction year is left raw (we
model demolitions, not lifespan; the year-1000 GIS marker is only flagged).
``cleaning_report`` records how many values each rule affects, overall and per indicator.

Outputs (written under ``results/``):
    ablation_summary.csv   one row per variant: counts, total/median m² + area coverage
    annual.csv             variant × year: count, m², and area coverage
    by_region.csv          variant × region: count, m², and area coverage
    cleaning_report.csv    total-area quality flags × (all stock, each indicator)
    overlap.csv            pairwise intersection + Jaccard among the 6 base indicators
    overlap_2018_2025.csv  same, restricted to dated 2018-2025 memberships
    figures/*.png + *.pdf  annual_counts, annual_area_total, overlap_heatmap
                           (rendered by src/plotting.py — seaborn, English labels)
"""

from __future__ import annotations

import argparse
from pathlib import Path

import polars as pl

import indicators as ind
import plotting

_ROOT = Path(__file__).resolve().parent.parent
RESULTS = _ROOT / "results"
FIGURES = RESULTS / "figures"

AREA_COL = "area_total"
OVERLAP_WINDOW = (2018, 2025)


# --- Per-building attribute rollup ------------------------------------------
# One row per building. Area/use/region taken as the LAST KNOWN non-null value over the
# building's full temporal history (its most recent registered state before exit). We
# verified max-over-history barely differs from the value at the status-10 row for the
# total-area column (+5.6k of 247k nulls recovered), so the nulls are genuine missingness,
# not blanked-on-exit — hence honest coverage reporting rather than backfill.


# Erroneous-value handling. We model DEMOLITIONS, not lifespan, so the only values that can
# corrupt an output are the ones we aggregate: the demolition DATE and the AREA. Negative
# total area is impossible and is filtered after candidate-event detection, using the same
# rule for every indicator. Zero total area is retained as a recorded value: it counts as
# non-null coverage, contributes 0 m², and is reported separately. The construction YEAR is
# a covariate we do not aggregate on, so its errors (0, medieval, or the auto-generated GIS
# marker 1000) are harmless here — nulling them would only discard real demolitions'
# metadata for no gain. We therefore leave construction_year RAW and merely FLAG the
# auto-generated year-1000 buildings (`autogenerated`) so a future lifespan /
# construction-period analysis can drop them itself (Andersen 2023 does).
AUTOGENERATED_YEAR = 1000  # GIS/satellite auto-registered buildings (flagged, NOT removed)


def _raw_rollup() -> pl.LazyFrame:
    """One row per building with the raw last-known non-null attributes (pre-cleaning)."""
    lf = pl.scan_parquet(ind.BYGNING_PATH).sort("virkningFra")

    def last_nonnull(col: str) -> pl.Expr:
        return pl.col(col).drop_nulls().last()

    return (
        lf.group_by("id_lokalId")
        .agg(
            last_nonnull("byg038SamletBygningsareal").alias("area_total"),
            last_nonnull("byg021BygningensAnvendelse").alias("use_code"),
            last_nonnull("region_name").alias("region_name"),
            last_nonnull("byg026Opførelsesår").alias("construction_year"),
        )
        .rename({"id_lokalId": "building_id"})
    )


def build_attributes() -> pl.LazyFrame:
    """One row per building with total area and carry-through attributes.

    ``area_total`` is the raw last-known non-null ``byg038SamletBygningsareal`` value:
    nulls and zeros are retained here. Negative values are filtered only after an
    indicator has selected its candidate buildings.
    """
    return _raw_rollup().select(
        "building_id",
        "area_total",
        "use_code",
        "region_name",
        "construction_year",  # left raw on purpose — see module note above
        (pl.col("construction_year") == AUTOGENERATED_YEAR).alias("autogenerated"),
    )


def _cleaning_flags() -> pl.DataFrame:
    """One boolean row per building: total-area quality flags plus the year-1000 flag.

    ``negative_total_area`` is the value actually excluded by the main analysis. Zero and
    missing total area are kept for counts and reported for coverage diagnostics. The
    ``autogenerated_year1000`` column is informational only — those years are kept.
    """
    raw = _raw_rollup().collect()
    return raw.select(
        "building_id",
        (pl.col("area_total") < 0).fill_null(False).alias("negative_total_area"),
        (pl.col("area_total") == 0).fill_null(False).alias("zero_total_area"),
        pl.col("area_total").is_null().alias("missing_total_area"),
        (pl.col("construction_year") == AUTOGENERATED_YEAR)
        .fill_null(False)
        .alias("autogenerated_year1000"),
    )


def cleaning_report(flags: pl.DataFrame) -> pl.DataFrame:
    """Values removed per rule — overall and per demolition indicator.

    Row ``ALL_BUILDINGS`` is the whole stock; each ``D#`` row counts only that indicator's
    demolished buildings hit. Negative total area is the analysis exclusion; zero/missing
    total area and ``autogenerated_year1000`` are kept flags reported for context.
    """
    rules = [
        "negative_total_area",
        "zero_total_area",
        "missing_total_area",
        "autogenerated_year1000",
    ]
    rows = [
        {"scope": "ALL_BUILDINGS", "n_buildings": flags.height}
        | {r: int(flags[r].sum()) for r in rules}
    ]
    for i in ind.all_indicators():
        ids = i.build().select("building_id").collect()
        sub = flags.join(ids, on="building_id", how="inner")
        rows.append(
            {"scope": i.id, "n_buildings": sub.height}
            | {r: int(sub[r].sum()) for r in rules}
        )
    return pl.DataFrame(rows)


# --- Per-variant statistics -------------------------------------------------


def _total_area_valid() -> pl.Expr:
    return pl.col(AREA_COL).is_null() | (pl.col(AREA_COL) >= 0)


def _coverage_aggs() -> list[pl.Expr]:
    area = pl.col(AREA_COL)
    positive = (area > 0).fill_null(False)
    zero = (area == 0).fill_null(False)
    return [
        area.is_not_null().sum().alias("buildings_with_non_null_area"),
        positive.sum().alias("buildings_with_positive_area"),
        zero.sum().alias("buildings_with_zero_area"),
        area.is_null().sum().alias("buildings_with_missing_area"),
        (area.is_not_null().mean() * 100).alias("area_coverage_pct"),
        (positive.mean() * 100).alias("positive_area_coverage_pct"),
        area.sum().alias("m2_total"),
        area.median().alias("median_m2_total"),
    ]


def summarise(label: str, demolished: pl.LazyFrame, attrs: pl.LazyFrame) -> pl.DataFrame:
    """One-row summary for a variant: count + total-area m²/median/coverage."""
    joined = demolished.join(attrs, on="building_id", how="left")
    before = joined.select(
        pl.len().alias("candidate_building_count_before_area_filter"),
        (pl.col(AREA_COL) < 0)
        .fill_null(False)
        .sum()
        .alias("negative_area_buildings_excluded"),
    ).collect()
    after = (
        joined.filter(_total_area_valid())
        .select(
            pl.len().alias("candidate_building_count_after_area_filter"),
            pl.len().alias("n_buildings"),
            pl.col("year").is_not_null().sum().alias("n_dated"),
            *_coverage_aggs(),
        )
        .collect()
    )
    return (
        pl.concat([before, after], how="horizontal")
        .insert_column(0, pl.Series("variant", [label]))
    )


def annual(label: str, demolished: pl.LazyFrame, attrs: pl.LazyFrame) -> pl.DataFrame:
    """variant × year: count + total-area m²/coverage (dated buildings only)."""
    joined = (
        demolished.join(attrs, on="building_id", how="left")
        .filter(pl.col("year").is_not_null())
        .filter(_total_area_valid())
    )
    out = (
        joined.group_by("year")
        .agg(pl.len().alias("n_buildings"), *_coverage_aggs())
        .sort("year")
        .collect()
    )
    return out.insert_column(0, pl.Series("variant", [label] * out.height))


def by_region(label: str, demolished: pl.LazyFrame, attrs: pl.LazyFrame) -> pl.DataFrame:
    """variant × region: count + total-area m²/coverage."""
    joined = demolished.join(attrs, on="building_id", how="left").filter(
        _total_area_valid()
    )
    out = (
        joined.group_by("region_name")
        .agg(pl.len().alias("n_buildings"), *_coverage_aggs())
        .sort("region_name")
        .collect()
    )
    return out.insert_column(0, pl.Series("variant", [label] * out.height))


def overlap(year_min: int | None = None, year_max: int | None = None) -> pl.DataFrame:
    """Pairwise intersection + Jaccard among the 6 base indicators (axis off).

    With a year window, only dated memberships inside the window are included.
    Undated case-only memberships cannot be assigned to a period, so they are
    excluded from windowed overlap while remaining part of the full-window table.
    """
    if (year_min is None) != (year_max is None):
        raise ValueError("year_min and year_max must be provided together")

    sets = {}
    for i in ind.all_indicators():
        members = i.build().select("building_id", "year")
        if year_min is not None and year_max is not None:
            members = members.filter(pl.col("year").is_between(year_min, year_max))
        sets[i.id] = set(members.select("building_id").unique().collect()["building_id"])

    rows = []
    ids = list(sets)
    for a in ids:
        sa = sets[a]
        for b in ids:
            sb = sets[b]
            inter = len(sa & sb)
            union = len(sa | sb)
            rows.append(
                {
                    "a": a,
                    "b": b,
                    "intersection": inter,
                    "jaccard": inter / union if union else 0.0,
                }
            )
    return pl.DataFrame(rows)


# --- Driver -----------------------------------------------------------------


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bygning", default=ind.BYGNING_PATH)
    ap.add_argument("--sagsniveau", default=ind.SAGSNIVEAU_PATH)
    ap.add_argument("--bbrsag", default=ind.BBRSAG_PATH)
    args = ap.parse_args()
    ind.BYGNING_PATH = args.bygning
    ind.SAGSNIVEAU_PATH = args.sagsniveau
    ind.BBRSAG_PATH = args.bbrsag

    RESULTS.mkdir(exist_ok=True)
    FIGURES.mkdir(exist_ok=True)

    print("Rolling up per-building attributes …")
    attrs = build_attributes().collect().lazy()  # materialise once, reuse across variants

    print("Reporting erroneous-value cleaning …")
    clean_df = cleaning_report(_cleaning_flags())
    clean_df.write_csv(RESULTS / "cleaning_report.csv")
    with pl.Config(tbl_cols=-1, tbl_rows=-1):
        print(clean_df)

    variants = ind.all_variants()
    summaries, annuals, regions = [], [], []
    for label, demolished in variants:
        print(f"  {label} …")
        summaries.append(summarise(label, demolished, attrs))
        annuals.append(annual(label, demolished, attrs))
        regions.append(by_region(label, demolished, attrs))

    summary_df = pl.concat(summaries)
    annual_df = pl.concat(annuals)
    region_df = pl.concat(regions)

    summary_df.write_csv(RESULTS / "ablation_summary.csv")
    annual_df.write_csv(RESULTS / "annual.csv")
    region_df.write_csv(RESULTS / "by_region.csv")

    print("Computing indicator overlap …")
    overlap_df = overlap()
    overlap_df.write_csv(RESULTS / "overlap.csv")
    overlap_window_df = overlap(*OVERLAP_WINDOW)
    overlap_window_df.write_csv(
        RESULTS / f"overlap_{OVERLAP_WINDOW[0]}_{OVERLAP_WINDOW[1]}.csv"
    )

    print("Rendering figures …")
    base = [i.id for i in ind.all_indicators()]  # base indicators only, for readability
    plotting.set_style()
    plotting.annual_lines(
        annual_df, "n_buildings", "Demolished buildings",
        "Annual demolition count by indicator", FIGURES / "annual_counts", base,
    )
    plotting.annual_lines(
        annual_df, "m2_total", "Demolished total area (m²)",
        "Annual demolished total area by indicator", FIGURES / "annual_area_total", base,
    )
    plotting.overlap_heatmap(
        overlap_df, "Indicator overlap (Jaccard)", FIGURES / "overlap_heatmap",
    )
    plotting.overlap_heatmap(
        overlap_window_df,
        f"Indicator overlap (Jaccard), {OVERLAP_WINDOW[0]}-{OVERLAP_WINDOW[1]}",
        FIGURES / f"overlap_heatmap_{OVERLAP_WINDOW[0]}_{OVERLAP_WINDOW[1]}",
    )

    print("\nSummary:")
    with pl.Config(tbl_cols=-1, tbl_width_chars=200, fmt_float="full"):
        print(summary_df)
    print(f"\nWrote tables + figures under {RESULTS}")


if __name__ == "__main__":
    main()
