"""Run the demolition-indicator ablation.

Each indicator in ``indicators.py`` returns only ``building_id`` + ``year`` — the
*membership* of the demolished set under that definition. This driver attaches the
outcome measures the article reports (``docs/indicators.md`` "Ablation scope") and
sweeps the full 14-cell variant grid (``all_variants``):

    - counts        — robust anchor (footprint area is ~complete, so counts are trustworthy)
    - demolished m² — under THREE area definitions, side by side, because the divergence
                      between them IS a result (secondary question 5), not a nuisance:
                        footprint  byg041BebyggetAreal          (~complete)
                        total      byg038SamletBygningsareal    (~54% null on demolished)
                        etage      byg039Bolig + byg040Erhverv  (BUILD basis; sparser still)
    - coverage %    — the fraction of demolished buildings with a non-null area, per column.
                      The papers drop missing-area buildings (Andersen 2023, explicit) and
                      don't report coverage; on THIS extract "drop missing" discards >50%,
                      so we sum available area with NO imputation and report coverage openly.

Per-building attributes (area, use-code, region, construction year) are rolled up from
``bygning.parquet`` here — this is aggregation plumbing, not a demolition decision, so it
lives in the driver, never in an indicator (the indicators stay pure per the article's
"no opaque contract" principle).

Erroneous AREA values (negative/zero) are coerced to null in ``build_attributes`` — buildings
are kept, so no indicator's count changes. Construction year is left raw (we model
demolitions, not lifespan; the year-1000 GIS marker is only flagged). ``cleaning_report``
records how many values each rule removed, overall and per indicator.

Outputs (written under ``results/``):
    ablation_summary.csv   one row per variant: counts, total/median m² + coverage per area def
    annual.csv             variant × year: count and m² per area def
    by_region.csv          variant × region: count and floor-area m²
    cleaning_report.csv    erroneous values removed per rule × (all stock, each indicator)
    overlap.csv            pairwise intersection + Jaccard among the 7 base indicators
    figures/*.png + *.pdf  annual_counts, annual_area_etage,
                           area_definition_sensitivity, overlap_heatmap
                           (rendered by src/plotting.py — seaborn, English labels)
"""

from __future__ import annotations

import argparse
from pathlib import Path

import polars as pl

import indicators as ind
import plotting

_ROOT = Path(__file__).resolve().parent.parent
RESULTS = _ROOT / "results"
FIGURES = RESULTS / "figures"

# The three area definitions swept side by side. `etage` (BUILD's bolig+erhverv basis)
# is derived below; the other two are raw columns. Order = increasing missingness.
AREA_DEFS = ["footprint", "total", "etage"]


# --- Per-building attribute rollup ------------------------------------------
# One row per building. Area/use/region taken as the LAST KNOWN non-null value over the
# building's full temporal history (its most recent registered state before exit). We
# verified max-over-history barely differs from the value at the status-10 row for the
# total-area column (+5.6k of 247k nulls recovered), so the nulls are genuine missingness,
# not blanked-on-exit — hence honest coverage reporting rather than backfill.


# Erroneous-value handling. We model DEMOLITIONS, not lifespan, so the only values that can
# corrupt an output are the ones we aggregate: the demolition DATE and the AREA. Those we
# clean. The construction YEAR is a covariate we do not aggregate on, so its errors (0,
# medieval, or the auto-generated GIS marker 1000) are harmless here — nulling them would
# only discard real demolitions' metadata for no gain. We therefore leave construction_year
# RAW and merely FLAG the auto-generated year-1000 buildings (`autogenerated`) so a future
# lifespan / construction-period analysis can drop them itself (Andersen 2023 does).
#
# Area cleaning IS applied to all three area columns with the same rule (`<= 0 → null`:
# negative is impossible, zero is "unregistered" not a real 0): buildings kept, so no
# indicator's count changes and `coverage_pct` stays honest. Future demolition DATES (the
# other modelled quantity) are removed by the demolition-year window in
# `indicators._in_window`; empirically there are none beyond the current year anyway.
AUTOGENERATED_YEAR = 1000  # GIS/satellite auto-registered buildings (flagged, NOT removed)


def _raw_rollup() -> pl.LazyFrame:
    """One row per building with the raw last-known non-null attributes (pre-cleaning)."""
    lf = pl.scan_parquet(ind.BYGNING_PATH).sort("virkningFra")

    def last_nonnull(col: str) -> pl.Expr:
        return pl.col(col).drop_nulls().last()

    return (
        lf.group_by("id_lokalId")
        .agg(
            last_nonnull("byg041BebyggetAreal").alias("area_footprint"),
            last_nonnull("byg038SamletBygningsareal").alias("area_total"),
            last_nonnull("byg039BygningensSamledeBoligAreal").alias("_bolig"),
            last_nonnull("byg040BygningensSamledeErhvervsAreal").alias("_erhverv"),
            last_nonnull("byg021BygningensAnvendelse").alias("use_code"),
            last_nonnull("region_name").alias("region_name"),
            last_nonnull("byg026Opførelsesår").alias("construction_year"),
        )
        .with_columns(
            # etageareal = bolig + erhverv (BUILD). Null only when BOTH are null (no info);
            # if one is present the other counts as 0. Negative components dropped first so
            # they cannot corrupt the sum.
            pl.when(pl.col("_bolig").is_null() & pl.col("_erhverv").is_null())
            .then(None)
            .otherwise(
                pl.when(pl.col("_bolig") >= 0).then(pl.col("_bolig")).otherwise(0)
                + pl.when(pl.col("_erhverv") >= 0).then(pl.col("_erhverv")).otherwise(0)
            )
            .alias("area_etage"),
        )
        .rename({"id_lokalId": "building_id"})
    )


def build_attributes() -> pl.LazyFrame:
    """LazyFrame[building_id, area_footprint, area_total, area_etage, use_code,
    region_name, construction_year, autogenerated] — one row per building.

    Area errors are coerced to null (footprint, total and etage all: ``<= 0`` = negative or
    "unregistered", same rule for the three). Construction year is left RAW — we model
    demolitions, not lifespan, so its errors do not corrupt any output — with the auto-
    generated year-1000 buildings only FLAGGED (`autogenerated`) for a downstream
    lifespan/construction-period analysis to drop.
    """
    return _raw_rollup().select(
        "building_id",
        # All areas: negative OR zero → null. Zero ground/floor area on a standing building
        # is "unregistered", not a real 0 (affects coverage%/median, not the sums). Same rule
        # for all three so footprint is not treated inconsistently.
        pl.when(pl.col("area_footprint") > 0).then(pl.col("area_footprint")).alias("area_footprint"),
        pl.when(pl.col("area_total") > 0).then(pl.col("area_total")).alias("area_total"),
        pl.when(pl.col("area_etage") > 0).then(pl.col("area_etage")).alias("area_etage"),
        "use_code",
        "region_name",
        "construction_year",  # left raw on purpose — see module note above
        (pl.col("construction_year") == AUTOGENERATED_YEAR).alias("autogenerated"),
    )


def _cleaning_flags() -> pl.DataFrame:
    """One boolean row per building: the area values coerced to null, plus the year-1000 flag.

    The three area flags count values actually *removed* (present raw → null). The last
    column, ``autogenerated_year1000``, is INFORMATIONAL only — those years are kept (we
    model demolitions, not lifespan); it just records how many carry the GIS marker.
    """
    raw = _raw_rollup().collect()
    return raw.select(
        "building_id",
        (pl.col("area_footprint") <= 0).fill_null(False).alias("zeroneg_footprint"),
        (pl.col("area_total") <= 0).fill_null(False).alias("zeroneg_total"),
        (pl.col("area_etage") <= 0).fill_null(False).alias("zeroneg_etage"),
        (pl.col("construction_year") == AUTOGENERATED_YEAR)
        .fill_null(False)
        .alias("autogenerated_year1000"),
    )


def cleaning_report(flags: pl.DataFrame) -> pl.DataFrame:
    """Values removed per rule — overall and per demolition indicator.

    Row ``ALL_BUILDINGS`` is the whole stock; each ``D#`` row counts only that indicator's
    demolished buildings hit (the "how many demolitions it affects" ask). The three area
    columns are removals; ``autogenerated_year1000`` is a *kept* flag reported for context.
    """
    rules = [
        "zeroneg_footprint",
        "zeroneg_total",
        "zeroneg_etage",
        "autogenerated_year1000",
    ]
    rows = [
        {"scope": "ALL_BUILDINGS", "n_buildings": flags.height}
        | {r: int(flags[r].sum()) for r in rules}
    ]
    for i in ind.all_indicators():
        ids = i.build().select("building_id").collect()
        sub = flags.join(ids, on="building_id", how="inner")
        rows.append(
            {"scope": i.id, "n_buildings": sub.height}
            | {r: int(sub[r].sum()) for r in rules}
        )
    return pl.DataFrame(rows)


# --- Per-variant statistics -------------------------------------------------


def summarise(label: str, demolished: pl.LazyFrame, attrs: pl.LazyFrame) -> pl.DataFrame:
    """One-row summary for a variant: count + per-area-def total/median/coverage."""
    joined = demolished.join(attrs, on="building_id", how="left")
    n = pl.len().alias("n_buildings")
    aggs = [n, pl.col("year").is_not_null().sum().alias("n_dated")]
    for a in AREA_DEFS:
        col = pl.col(f"area_{a}")
        aggs += [
            col.sum().alias(f"m2_{a}"),
            col.median().alias(f"median_m2_{a}"),
            (col.is_not_null().mean() * 100).alias(f"coverage_pct_{a}"),
        ]
    return joined.select(aggs).collect().insert_column(0, pl.Series("variant", [label]))


def annual(label: str, demolished: pl.LazyFrame, attrs: pl.LazyFrame) -> pl.DataFrame:
    """variant × year: count + m² per area def (only dated buildings contribute)."""
    joined = demolished.join(attrs, on="building_id", how="left").filter(
        pl.col("year").is_not_null()
    )
    aggs = [pl.len().alias("n_buildings")] + [
        pl.col(f"area_{a}").sum().alias(f"m2_{a}") for a in AREA_DEFS
    ]
    out = joined.group_by("year").agg(aggs).sort("year").collect()
    return out.insert_column(0, pl.Series("variant", [label] * out.height))


def by_region(label: str, demolished: pl.LazyFrame, attrs: pl.LazyFrame) -> pl.DataFrame:
    """variant × region: count + etageareal m²."""
    joined = demolished.join(attrs, on="building_id", how="left")
    out = (
        joined.group_by("region_name")
        .agg(
            pl.len().alias("n_buildings"),
            pl.col("area_etage").sum().alias("m2_etage"),
        )
        .sort("region_name")
        .collect()
    )
    return out.insert_column(0, pl.Series("variant", [label] * out.height))


def overlap() -> pl.DataFrame:
    """Pairwise intersection + Jaccard among the 7 base indicators (axis off)."""
    sets = {
        i.id: i.build().select("building_id").collect()["building_id"]
        for i in ind.all_indicators()
    }
    rows = []
    ids = list(sets)
    for a in ids:
        sa = set(sets[a])
        for b in ids:
            sb = set(sets[b])
            inter = len(sa & sb)
            union = len(sa | sb)
            rows.append(
                {
                    "a": a,
                    "b": b,
                    "intersection": inter,
                    "jaccard": inter / union if union else 0.0,
                }
            )
    return pl.DataFrame(rows)


# --- Driver -----------------------------------------------------------------


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bygning", default=ind.BYGNING_PATH)
    ap.add_argument("--sagsniveau", default=ind.SAGSNIVEAU_PATH)
    ap.add_argument("--bbrsag", default=ind.BBRSAG_PATH)
    args = ap.parse_args()
    ind.BYGNING_PATH = args.bygning
    ind.SAGSNIVEAU_PATH = args.sagsniveau
    ind.BBRSAG_PATH = args.bbrsag

    RESULTS.mkdir(exist_ok=True)
    FIGURES.mkdir(exist_ok=True)

    print("Rolling up per-building attributes …")
    attrs = build_attributes().collect().lazy()  # materialise once, reuse across variants

    print("Reporting erroneous-value cleaning …")
    clean_df = cleaning_report(_cleaning_flags())
    clean_df.write_csv(RESULTS / "cleaning_report.csv")
    with pl.Config(tbl_cols=-1, tbl_rows=-1):
        print(clean_df)

    variants = ind.all_variants()
    summaries, annuals, regions = [], [], []
    for label, demolished in variants:
        print(f"  {label} …")
        summaries.append(summarise(label, demolished, attrs))
        annuals.append(annual(label, demolished, attrs))
        regions.append(by_region(label, demolished, attrs))

    summary_df = pl.concat(summaries)
    annual_df = pl.concat(annuals)
    region_df = pl.concat(regions)

    summary_df.write_csv(RESULTS / "ablation_summary.csv")
    annual_df.write_csv(RESULTS / "annual.csv")
    region_df.write_csv(RESULTS / "by_region.csv")

    print("Computing indicator overlap …")
    overlap_df = overlap()
    overlap_df.write_csv(RESULTS / "overlap.csv")

    print("Rendering figures …")
    base = [i.id for i in ind.all_indicators()]  # base indicators only, for readability
    plotting.set_style()
    plotting.annual_lines(
        annual_df, "n_buildings", "Demolished buildings",
        "Annual demolition count by indicator", FIGURES / "annual_counts", base,
    )
    plotting.annual_lines(
        annual_df, "m2_etage", "Demolished floor area (m²)",
        "Annual demolished floor area by indicator", FIGURES / "annual_area_etage", base,
    )
    plotting.area_definition_bars(
        summary_df, AREA_DEFS,
        "Area-definition sensitivity: same indicator, three area columns",
        FIGURES / "area_definition_sensitivity", base,
    )
    plotting.overlap_heatmap(
        overlap_df, "Indicator overlap (Jaccard)", FIGURES / "overlap_heatmap",
    )

    print("\nSummary:")
    with pl.Config(tbl_cols=-1, tbl_width_chars=200, fmt_float="full"):
        print(summary_df)
    print(f"\nWrote tables + figures under {RESULTS}")


if __name__ == "__main__":
    main()
